<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "sendcloud": {
                        "component": "SendCloud_SendCloud/js/servicePoint/view/checkout/shipping/servicePoint",
                        "scriptUrl": "<?= /* @escapeNotVerified */ $block->getScriptUrl()?>"
                    }
                }
            }
        }
    }
</script>
<script>
    var storeLocale = "<?= /* @escapeNotVerified */ $block->getLocale()?>";
    var translations = <?= /* @escapeNotVerified */ json_encode($block->getTranslations())?>;
</script>
