<div class="admin__field">
    <div class="admin__field-label modal-field-label">
        <b><?= /* @escapeNotVerified */
            $escaper->escapeHtml($block->getFreeShipping()); ?></b>
    </div>
    <div class="admin__field-label modal-field-label">
        <b><?= /* @escapeNotVerified */
            $escaper->escapeHtml($block->getDefaultRate()); ?></b>
    </div>
</div>
<?php if ($block->getRates()): ?>
    <?php if ($block->isServicePoint()): ?>
        <table class="data-grid data-grid-draggable">
            <thead>
            <tr>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content">Carriers</span>
                </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getCarriers() as $carrier): ?>
                <tr>
                    <td>
                        <div class="data-grid-cell-content"><?= $carrier; ?></div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
    <?php if (!$block->isServicePoint() || !$block->isServicePointLegacyRates()): ?>
        <table class="data-grid data-grid-draggable">
            <thead>
            <tr>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content">Weight class</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content">Shipping rate</span>
                </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getRates() as $rate): ?>
                <tr>
                    <td>
                        <div class="data-grid-cell-content"><?= $rate['weight']; ?></div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content"><?= $rate['rate']; ?></div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>
<div class="pp-buttons-container">
    <a href=<?= $block->getEditLink(); ?> target="_blank"><input id="edit_btn" type="button"
                                                                 value="Edit rates in Sendcloud"></a>
</div>
