<div class="sendcloud-branding">
    <div class="logo-wrap">
        <img width="123" src="<?= /* @escapeNotVerified */ $block->getSendCloudLogo() ?>"/>
    </div>
    <div class="content">
        <p>
            <?=__('Sendcloud | The Number 1 Shipping Tool | Contact ');?>
            <a href="<?= /* @escapeNotVerified */ $block->getSendCloudUrl() ?>" target="_blank">Sendcloud</a> <?=__('for support and more information.');?>
    </div>
</div>
