<div class="pp-buttons-container">
    <button id="<?php echo $block->getId() ?>" onclick="return false;">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
</div>

<script>
    require([
        'jquery',
        'prototype'
    ], function($){
        $('#connectToSendCloud').click(function () {
            var w = window.open('<?php echo $block->getAjaxCheckUrl()?>');
            $.ajax({
                url: "<?php echo $block->getAjaxCheckUrl() ?>",
                method: 'POST',
                data: {form_key: window.FORM_KEY},
                success: function (response) {
                    w.location = response.url;
                }
            });
            return false;
        });

    });
</script>