<div class="pp-buttons-container">
    <button id="<?php echo $block->getId() ?>" onclick="return false;">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
</div>

<script>
    require([
        'jquery',
        'prototype'
    ], function($){
        console.log('<?php echo $block->getAjaxCheckUrl() ?>');
        $('#connectToSendcloud').click(function () {
            $.ajax({
                url: "http://192.168.70.70/backend/creativeict_autoconnect/autoconnect/index/",
                method: 'POST',
                data: {form_key: window.FORM_KEY},
                success: function (response) {
                    console.log(response)
                }
            })

        });

    });
</script>