<?php
/**
 * Copyright © Creative CT
 * Override | added SendCloud tracking url
 */
?>
<?php /* @var \Magento\Framework\View\Element\Template $block */ ?>
<?php $_shipment = $block->getShipment() ?>
<?php
/* @var \Magento\Sales\Model\Order $_order */
$_url = 'https://tracking.sendcloud.sc/forward?';
$_order = $block->getOrder();
$_countryId = $_order->getShippingAddress()->getCountryId();
$_postcode = str_replace(' ', '+', $_order->getShippingAddress()->getPostcode())?>
<?php if ($_shipment && $_order) : ?>
    <?php $trackCollection = $_order->getTracksCollection($_shipment->getId()) ?>
    <?php if ($trackCollection) : ?>
        <br />
        <table class="shipment-track">
            <thead>
            <tr>
                <th><?= $block->escapeHtml(__('Shipped By')) ?></th>
                <th><?= $block->escapeHtml(__('Tracking Number')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($trackCollection as $_item) : ?>
                <tr>
                    <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                    <td>
                        <?php if ($_item->isCustom() && $_order->getShippingMethod() == 'sendcloud_sendcloud') : ?>
                            <a href="<?= $_url .
                                'carrier=' . strtolower($_item->getTitle()) .
                                '&code=' . $block->escapeHtml($_item->getNumber()) .
                                '&destination=' . $_countryId .
                                '&verification=' . $_postcode ?>"
                                target="_blank">
                        <?php else : ?>
                            <a href="<?= $block->escapeUrl($block->getTrackingUrl()->getUrl($_item)) ?>" target="_blank">
                        <?php endif; ?>
                            <?= $block->escapeHtml($_item->getNumber()) ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>
